### ISSUE TITLE
v0.4 is not published on https://galaxy.ansible.com/gcoop-libre/mysqldump/

### ISSUE THREAD

**Issue by thiagogomesverissimo** [gcoop-libre/ansible-role-mysqldump#1]

**Comment by osiris** [comment]
DONE

Starting import 233544: role_name=mysqldump repo=gcoop-libre/ansible-role-mysqldump
Accessing branch: master
Parsing and validating meta data.
Parsing galaxy_tags
Parsing platforms
Parsing cloud platforms
No cloud platforms found in meta data
Parsing and validating README
Adding repo tags as role versions
Removing old tags
Import completed
Status SUCCESS : warnings=1 errors=0

thanks for reminder!
